version: '3.8'
services:
  dev-db:
    container_name: 'spring-boot-amogoscode'
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: student
    networks:
      - thinuradev
networks:
  thinuradev: